### ISSUE TITLE
A way to build Demo/SpoutSender.exe and Demo/SpoutReceiver.exe

### ISSUE THREAD

**Issue by fortminors** [leadedge/Spout2#109]
Hello! I've noticed your recent commits delete the DEMO folder alongside other binaries. The demo SpoutSender.exe and SpoutReceiver.exe were very useful for tests. Is there a way to build them with the newest code base?

And if I use the old SpoutSender.exe, is it compatible with the newest builds using SpoutDX?

**Comment by leadedge** [comment]
The demo sender and receiver are part of the [Spout release](https://github.com/leadedge/Spout2/releases). All the binaries are now available in the release rather than the repository itself.

The demo program is now in a [separate repository](https://github.com/leadedge/ofSpoutDemo). You can build either sender or receiver from the single program. There is a dependency on Openframeworks but otherwise all the required files are included.

The older demo sender and receiver are still compatible.
