### ISSUE TITLE
Spout with WebGPU

### ISSUE THREAD

**Issue by h-a-n-n-e-s** [leadedge/Spout2#111]
Is it possible to share some buffers from an app using **WebGPU** in the browser with another app which uses Spout (in this case TouchDesigner)?
Thanks!

**Comment by leadedge** [comment]
I don't think this would be impossible, but I don't know enough about WebGPU to suggest how it could be done. You would have to write some functions to link WebGPU textures with the OpenGL textures used in the Spout SDK. After a quick search I came across [this tutorial](https://eliemichel.github.io/LearnWebGPU/index.html) that might be a good start.

**Comment by h-a-n-n-e-s** [comment]
Thanks a lot for your quick reply!

Sorry to bother you, but I'm kind of lost and don't know where to start, so I have some very basic questions regarding the overall process and data flow.

1. Is it necessary to set up some kind of Spout sender with a **native app** written in cpp? Is this the reason you suggested [this cpp WebGPU tutorial](https://eliemichel.github.io/LearnWebGPU/index.html)? I have some basic knowledge of [wgpu](https://github.com/gfx-rs/wgpu) with Rust, could I use wgpu as well?

2. My app running in the browser would then connect to this Spout sender by writing to some shared OpenGL textures? Or what would be the overall process and data flow?

3. Which of the files, or which sdk in [Spout2](https://github.com/leadedge/Spout2) would I actually need to set up such a Spout sender? Would it be SpoutGL?

4. Unfortunately, while the final product is supposed to run on Windows, I am developing on Mac. Is the process to do a test setup with Syphon similar to Spout or would I have to rewrite everything?

Any additional background would be welcome!
Thank you!

**Comment by leadedge** [comment]
I am not familiar enough with WebGPU to answer how to interface with it, but basically if it is based on OpenGL, you would use the "SpoutGL" files in a C++ application. That's why the suggested tutorial is relevant. The Spout sender would be a sender object :

```
#include "Spout.h"

Spout mySender;
```

First give it a name significant to you :

`mySender.SetSenderName("WebGPUsender");`

The application would need to find the rendering procedure and from that get an OpenGL texture or Fbo for the sending functions. The texture cannot be mipmapped. It can have only one level.

You might be lucky if there is an OpenGL fbo (backbuffer) underlying the rendering and you could try :

`mySender.SendFbo(0, 0, 0);`

Spout is Windows only. Look at Syphon for the Mac. You might not have to re-write everything but would need to follow the requirements of the Syphon framework.

There are some [open source projects](https://leadedge.github.io/spout-projects.html#Rust) using Rust with Spout. This might introduce another layer to complicate the process but it could give you some ideas.

**Comment by h-a-n-n-e-s** [comment]
Ok, I think I got a basic idea now. Thanks a lot!

**Comment by leadedge** [comment]
Please post in English .

Translation
`I also need this function currently. I am writing a program in this area myself. It would be perfect if the author could provide a desktop interface for spout2. You have to know that many people are using the Vtube Studio software. It comes with spout video stream output, but He does not have the ability to display table pets`
