### ISSUE TITLE
Sometime SpoutSharedMemory::Unlock() assert(m_lockCount >= 0)

### ISSUE THREAD

**Issue by Qlex42** [leadedge/Spout2#15]
Hi
My application is multi-threaded  (gui and opengl have different threads) 
I'm also using shared multi opengl context.
I avoid Spout API concurrent calls with a custom global mutex.
I'm using the last Master branch version of Spout2

In very rare case, SpoutSharedMemory::Unlock() assert(m_lockCount >= 0) 
in SpoutSharedMemory.cpp at line 235
This is because spoutMemoryShare::LockSenderMemory() call SpoutSharedMemory::Unlock() when SpoutSharedMemory::Lock() fail in SpoutSenderMemory.cpp at line 196. 

As other Lock() callers, this function should not call Unlock() when Lock() fail. This made the m_lockCount value negative and introduce further problems...

From a general point of view, I'm not convicted about the needs of the m_lockCount variable:
MSDN ReleaseMutex documentation says that: A thread can specify a mutex that it already owns in a call to one of the wait functions without blocking its execution. This prevents a thread from deadlocking itself while waiting for a mutex that it already owns. However, to release its ownership, the thread must call ReleaseMutex one time for each time that it obtained ownership (either through CreateMutex or a wait function).

Thanks for your interest about this issue.

Regards,

**Comment by leadedge** [comment]
Thanks for tracking this down so that it is an easy fix. I checked through "SpoutSenderNames.cpp" where the memory map locks are most frequently used and it is OK.

The purpose of the "SpoutMemoryShare" class is to provide a backup when texture sharing fails, so in most cases it will not be used.

I would seek advice about the "SpoutSharedMemory" class from the author Malcolm Bechard, but if using the m_lockCount variable is causing no harm I would leave it alone.

**Comment by leadedge** [comment]
Fixed

**Comment by Qlex42** [comment]
I just merge the master branch, thanks for this fix.
