### ISSUE TITLE
Updating ofxSpout with latest SDK creates error in example send project

### ISSUE THREAD

**Issue by Harvey3141** [leadedge/Spout2#19]
Hi, 

I'm about to update ofxSpout (https://github.com/elliotwoods/ofxSpout) with the latest spout SDK, after updating the src files in _ofxSpout\libs\SpoutSDK\src_ , the example send project fails to compile with this error,

_error C4703: potentially uninitialized local pointer variable 'exc' used_

In spoutglextensions.cpp on line 415

Thanks,

Harvey

**Comment by leadedge** [comment]
This is due to a debugging print statement within a function to test at runtime for GL_EXT_bgra extensions. The error is not picked up by VS2012. It has some problems so is not used. The files are updated with that function commented out.

If GL_EXT_bgra extensions are not available, the symptom will be reversal of colours when using "SendImage" and "ReceiveImage". I believe this will be rare and the check can be removed in any case.
