### ISSUE TITLE
Build SpoutPanel.exe

### ISSUE THREAD

**Issue by ignaciosw** [leadedge/Spout2#20]
Hi, I was trying to compile and build a new executable with the source code of SpoutPanel.

Not quite reaching anything with visual studio or Mingw

Any suggestion on how to re build it? thanks

**Comment by leadedge** [comment]
I have included the source for reference only. So I have included a VS2012 project file and re-ordered the folders so that it should build. 

You need to set up folders as on Github with the first SpoutPanel folder at the same level as the Spout SDK files. You only need SpoutSenderNames.cpp/h and SpoutSharedMemory.cpp/h.

I doubt that it will work with MingW due to the use of std::unordered_map and std::set.

Why do you need to rebuild it? I would like to hear of any modifcations that should be made.

**Comment by ignaciosw** [comment]
Thanks for your reply
I was trying to see if I could make a version of the exe that was runnable from commandline and select a Spout Sender on the fly for different receivers that I have in a Processing app. No major modif, just a tweaking to test something locally. If it should work, would you like a stable version of it? thanks!

**Comment by leadedge** [comment]
It was probably relative folder locations. I am using VS2012 express.

Sure please send me whatever you end up with. SpoutPanel uses the command line so maybe you can add arguments like "- dothis" and "- dothat".

I am not sure how you want it to work, but you might not need to rebuild SpoutPanel.  Look at SpoutSDK.cpp - SelectSenderPanel.

Then the trick is to know what the user has selected. SpoutPanel writes the selected sender to the registry and you can get it from there. You will find that in CheckSpoutPanel(). In fact this is used every time ReceiveTexture is called, so you just have to call SelectSenderPanel and it is all done for you.

Anyway I am not sure how you want it to work but there are plenty of ideas to start with.

**Comment by ignaciosw** [comment]
Thanks.
Basically I want it to work like SpoutPanel.exe -sender=mysender1

arguments with name and value. I guess I'll have to tweak it a bit? and also can I call SelectSenderPanel() from main.cpp ?

**Comment by ignaciosw** [comment]
Nevermind. Achieved.

**Comment by leadedge** [comment]
Good luck with this. You know where to contact me.
