### ISSUE TITLE
FFGL Compile

### ISSUE THREAD

**Issue by perrelet** [leadedge/Spout2#22]
Hey there,

So grateful for the pure awesomeness that is spout.

I'm attempting to compile and run the FFGL receiver. However when I define `SpoutReceiver receiver;` in my header the .dll no longer displays in the host. (There are no compile errors.)

I'm currently using the Spout.lib in my linker. I've also recompiled the lib, but no joy there. Should I try and use the dll version instead? `#define SPOUT_IMPORT_DLL` - If so where is the most sensible location for the dll?

Any help would be much appreciated,

Thankyou.

**Comment by leadedge** [comment]
If you are using the Spout SDK as a dll and link to the lib file, the dll has to be accessible by the application. If the application is a dll, sometimes you can put the Spout dll in the same folder but sometimes it has to be in the same folder as the host executable (e.g. for Resolume).

Somebody else was using "SpoutLibary" in a freeframe dll. That works too if you want to, but generally I do not use a dll for Spout within a freeframe dll, but rather include all the Spout source files in the project and in the header file include "#include SpoutReceiver.h" with a suitable path.

This does not disturb the Freeframe extensions unless you use fbo functions directly in your code. Then you need to then use the Freeframe extensions for fbo.

Also be aware of the bug in Freeframe 1.5 for string inputs as mentioned in the ShaderLoader issue because the receiver dll uses a string for name input.
