### ISSUE TITLE
SpoutCam

### ISSUE THREAD

**Issue by peteshand** [leadedge/Spout2#32]
Hey there

Just discovered Spout today, I gotta say from what I've seen so far this looks like a really great piece of software!
I do however have a question relating to SpoutCam.

I saw this youtube video (https://www.youtube.com/watch?v=Vy6yyFjNATI) showing how to use it, however it looks like the video is for Spout1 and the files have changed (ie: no SpoutTray anymore). The only exe relating to SpoutCam i can see in this repo is SpoutCamSettings.exe, launching this shows a dialog box where i can select fps and resolution with an ok and cancel button. After clicking ok the dialog disappears and that's it, can't see any related process running. Am i missing something obvious? is there any 3rd party dependencies?

Finally is there any cli for SpoutCam?

**Comment by leadedge** [comment]
Really sorry - that video is out of date. But SpoutCam hasn't changed much. "SpoutCamSettings" will set fps and resolution which will take effect the next time SpoutCam starts. There are no dependencies or anything. 

No there is no command line because SpoutCam is not an executable program. It is registered by the installer as if is was a real webcam, although is is a virtual webcam. Most programs that recoginise DirectShow webcams will find it. Then you just select it as if it was a real webcam.

**Comment by peteshand** [comment]
Looks like it's just not compatible what the program I was trying to use it with :/
Thanks anyway

**Comment by leadedge** [comment]
Yes many programs don't support DirectShow. SpoutCam is based on fairly old code.

**Comment by peteshand** [comment]
Trying to load the SpoutCam with a few methods.. html5 and Adobe AIR. Do you know if anyone else has tried to use it this way?

**Comment by leadedge** [comment]
No I don't know if that is possible. It could be but I am not familiar enough with Adobe Air to say. 

Once registered, SpoutCam is available through DirectShow. If your programs support DirectShow you might have some success. A good resource for testing and understanding DirectShow is "GraphEdit" or "GraphStudio" - http://blog.monogram.sk/janos/tools/monogram-graphstudio/ .

The thing to keep in mind is that SpoutCam simulates a webcam, so if your programs pick up a typical webcam it is possible that SpoutCam will be in the list of available webcams.

**Comment by peteshand** [comment]
Ok, no worries
