### ISSUE TITLE
Create a Receiver without Sender

### ISSUE THREAD

**Issue by Golem235** [leadedge/Spout2#40]
Hello, 
I like to create a Receiver without having the Sender initialized at that moment. 

When I try to, the function CreateReceiver returns false and there is no Receiver created. 

Is there a way to create the Receiver before the Sender is created?

**Comment by leadedge** [comment]
Perhaps "CreateReceiver" is not the best name for the function.

A receiver is declared either as an object in the header file or as a pointer and the object created in the application as necessary. That is all you need to do in advance.

A receiver has information about the sender it receiving from. If it is not receiving, then there is no information and it is not yet "Created".

The CreateReceiver function will look for a sender and connect to it when found, so the function can be called repeatedly in a loop until a sender is detected.

**Comment by Golem235** [comment]
Thank you for your response.
In my case, unfortunately, I have no access to the GLextentions in my render loop.
Therefore, I would like to have created the receiver at the beginning of the program and receive only the image in the render loop. Data, such as the width and height of the image are already known to me at the time.

I do not currently transfer any texture but an image as unsigned char *.

Is there still no way to create the receiver initially and only receive the image in the render loop?

**Comment by leadedge** [comment]
Cold you explain more about what the problem is? Do you mean that you have no OpenGL context in the render loop? If so, the OpenGL texture sharing functions will fail, including ReceiveImage. Is the render loop in a separate thread?

It might be possible with memoryshare mode if you use ReceiveImage in the render loop with the known sender name and width and height, but I am not sure. You would have to set memoryshare mode in SpoutSettings and both the sender and your program would have to be started after the mode is set.

This is not very useful and if there is a separate thread for the render loop which does not have an OpenGL context it might be possible to create one using "receiver.spout.interop.InitOpenGL()".

**Comment by Golem235** [comment]
Thank you very much, you saved my day. 
I already used the memorysharemode but without openGL the receiver wasn't able to load the GLextentions. 

Running receiver.spout.interop.InitOpenGL() first, the receiver is able to connect and receive my image.

**Comment by leadedge** [comment]
OK that's good to know.
