### ISSUE TITLE
Glitch error in resolume with spout from unity 

### ISSUE THREAD

**Issue by CNDSD** [leadedge/Spout2#42]
Hi! First, thanks for creating this library, it's really useful.

I have an error when passing my interaction of unity to resolume on the screen, the frames freeze, and it seems an error, a kind of glitch, does not allow it to look the same as what is seen in the helmet (live htc).

Will they have any idea what is happening, or should I change some configuration in unity?

In resolume is within a layer without any effect, it seems that the error comes from unity, I do not know if it is compatibility of frames.

Hopefully you can support me, I send images, this is for an exhibition in Mexico that will be this week! uups

Thanks!

![IMG_4806](https://user-images.githubusercontent.com/10885208/65397297-8cd19100-dd74-11e9-9f93-7b3379068135.JPG)

**Comment by leadedge** [comment]
It's hard to know where the problem could be. I have had similar reports with Unity but can't advise on that. Perhaps the plugin developer might have some suggestion. DirectX 9 mode can cause problems with Resolume. Check "DirectX 9" off  in SpoutSettings. Sometimes NVIDIA settings can cause hesitations or stutter. Disable "Threaded Optimization" using the NVIDIA control panel.

**Comment by CNDSD** [comment]
Thanks! i try also this  but, nothing the same result always :( , thanks

**Comment by leadedge** [comment]
There are too many variables for me to guess where the problem is. I would try to isolate the cause by eliminating each process individually, but this could take some time and it does not help with the immediate exhibition.

If you are using the KlakSpout plugin (https://github.com/keijiro/KlakSpout), you could try Newtek NDI and his plugin for that (https://github.com/keijiro/KlakNDI). Resolume supports NDI in and out.

NDI is designed for transfer between applications over a network but it also works on a local machine. It is not as fast but might get you going for the event.

You would need to download and install the NDI tools package (https://ndi.tv/tools/#) and get that working first, then get the unity plugin working.

**Comment by leadedge** [comment]
I can't resolve this problem. Closing old issue.
