### ISSUE TITLE
Spout DX11 receiver cannot receive image from Spout sender from UE4

### ISSUE THREAD

**Issue by ericdlee** [leadedge/Spout2#47]
Hi,

I'm integrating Spout DX11 receiver in my project. It works for most of the cases. But recently when I tried to get image from UE4 it fails. Here are the details.
Sender: Spout plugin for UE4(https://github.com/AleDel/Spout-UE4)
Receiver: SDK D3D11 tutorial07
I compared with original Spout receiver. It works fine.
![image](https://user-images.githubusercontent.com/3919180/77984975-b253de80-7345-11ea-9cc1-e5c6dda1f067.png)
Can you help to locate the issue? Thanks!

**Comment by ericdlee** [comment]
I read the similar issue of U3D plugin. Looks like something related with the UE4 plugin. :(

**Comment by leadedge** [comment]
I have been working on the DX11 examples a little while back for another project and found the same problem. It's a tricky one. Both UE4 and U3D use a DirectX11 texture created by the application. The Tutorial07 example copies the sender's shared texture directly (instead of by way of the OpenGL/DirectX interop) and uses that texture as a shader resource view. There are limitations for a shader resource view such as matching format. The first question is - in your own application are you using the received texture as a shader resource view? I will have to refresh my memory of the project work before I can suggest anything more.

**Comment by ericdlee** [comment]
Yes. Same as tutorial07.

**Comment by leadedge** [comment]
I have uploaded a test executable for Tutorial07 for you to try with UE4 -
[https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/Examples/DX11example/Binaries](https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/Examples/DX11example/Binaries)
If it works I will update the Spout SDK and SpoutDX class.

**Comment by ericdlee** [comment]
Sorry the new testing executable show black image. :(
![image](https://user-images.githubusercontent.com/3919180/78090977-441f2280-73fe-11ea-9253-1b92e11e2602.png)

**Comment by leadedge** [comment]
At least it's different. I am not sure what I can do without any means to test and work with this. I will give it a little more thought.

**Comment by ericdlee** [comment]
Thanks for your kindly support. I will also update if I find any clue in UE4.

**Comment by leadedge** [comment]
I think it's something to do with the creating the shader resource view,  it seems to be something to do with formats, but there could be more to it.

A while back I had a similar problem with a DirectX 9 sender where the texture format was not compatible  with another program. I made a bridging program which solved the problem. This might work for UE4 and get you going. Contact me by email for details.

**Comment by leadedge** [comment]
For readers with a similar problem, contact me via email. There is a bridging program that allows a workaround. I have not been able to find the underlying cause but will keep it in mind.
