### ISSUE TITLE
Using Spout with D3D11 directly ? 

### ISSUE THREAD

**Issue by jcelerier** [leadedge/Spout2#49]
Hello,
Is there a guide / way to use Spout directly with an existing D3D11 texture ? 

To give some context, I'm trying to add Spout support to https://github.com/OSSIA/score

The GPU pipeline is handled by the Qt RHI (https://www.qt.io/blog/qt-quick-on-vulkan-metal-direct3d) which is an abstraction over GL/DX11/Vulkan/Metal. If possible, I'd like to use DX11 on Windows - I already have it working with Spout under GL though so it's not a very big deal, but it could lead to some perf. improvement.

My understanding is that with DX11, I could set the shared ID3D11Texture2D as my render pipeline's final render target, and then notify Spout that rendering has been done, maybe with some level of locking before that. Thus there would be no copies of gl textures to D3D textures or things like that.

Is this something achievable somehow ? 
Thanks !

**Comment by leadedge** [comment]
Yes for 2.006 there are : 

bool spoutGLDXinterop::WriteTexture(ID3D11Texture2D** texture)
bool spoutGLDXinterop::ReadTexture(ID3D11Texture2D** texture)

For a sender you have to make sure the sender is created and the texture sizes match. A receiver has to monitor the sender size to make sure the receiving texture is updated.

I have been working on [DirectX examples](https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/Examples/DX11example). You could use the beta code, but I am not happy with the SpoutDX class and it's under revision. Hopefully the examples will give you some idea.

The important thing to note is use of the sender mutex before the shared texture is copied. The 2.007 methods include a frame counter, but that can be removed for 2.006 applications.

Problems I have found are. Matching format is important if you want to create a shader resource view of the received texture. If the sending texture has a keyed mutex, it must be accessed or the texture will not be copied. You will have to check for this if the texture is used to interface with a Vulkan image. I will be updating the mutex check to include keyed mutex if the texture has one.

It might seem ideal to access the sender's shared DirectX texture directly, but it is not that simple. The main difficulty is with CopyResource which is asynchronous. The received texture might not be updated immediately, depending on the command queue. This means that a receiver will display a new frame after a random delay. If this happens to occur right on vertical sync, you could see hesitations.

To overcome that I have introduced a flush and wait until CopyResource is finished. This is not a problem if the DirectX device is created simply for the purpose of creating and copying textures, because there is no queue. But it could be a problem if the application device is used and the command queue is backed up. Then you might get a stall. This is extremely difficult to test, so it is a matter of trying it with or without the flush.

So it is achievable with some caution. The Unity and Unreal Engine plugins use DirectX texture copy already and they are having success. I think they shoud use the sender mutex but it seems to be working for them.

**Comment by jcelerier** [comment]
Thanks, that's great, will try to integrate it like that !
