### ISSUE TITLE
Discrete Spout to NDI

### ISSUE THREAD

**Issue by Franck-J8** [leadedge/Spout2#60]
Hi,
We've tested "Spout to NDI" that looks performant and stable so far.
We would like to use it in a more discrete way, without a gui, as a mutli-instantiated service.
Do you plan to release the source ?
Perhaps we can contribute with creating this discrete version ? as we think it can be wanted and used by more people.

**Comment by leadedge** [comment]
I don't plan to release the source because it adds to the number of repositories I have to maintain and I have limited time.

I have changed this from a Windows program to Openframeworks for the same reason. Now I use addons which can be independently maintained. The application uses "ofxWinMenu" for the gui, "ofxXmlSettings" to read and write user settings and "ofxNDI" for the NDI functions.

If you are not using Openframeworks you can use a sub-set of the ofxNDI files, but then you have to handle OpenGL or DirectX texture <> CPU for NDI, which can be done either by yourself or using methods taken from the Spout SDK.

If I was to do what you want to do,  I would look at a headless Openframeworks program or a Windows tray application or something like that.

As I say, I will not be publishing the source, but you are welcome to it if you send email via the spout@etc address on the GitHub overview page. You should be able to get it working  as-is before looking at modifications.

If you think this would be a useful thing for people to work with, maybe you could consider a GitHub repository. I could assist with the ofxNDI addon if you need help with that.

**Comment by Franck-J8** [comment]
Thank you for your level of assistance.
That's very good options.

**Comment by leadedge** [comment]
OK Franck,
now you have working copy of the Spout to NDI project so you should get something out of that.
I will close this now and I hope to hear the result of your project.
