### ISSUE TITLE
Laptops with multiple GPUs

### ISSUE THREAD

**Issue by creativewax** [leadedge/Spout2#70]
having weird issues on a couple of laptops with multiple GPUs were sometimes I am just hit with white noise when sending data across, and then randomly sometimes without any changes the actual texture data is sent fine, but only seems to be with machines with multiple GPUs I have isolated it too, wondering if anyone knows why?

**Comment by leadedge** [comment]
Are you using "SpoutCam" virtual webcam? This generates white noise when no sender texture is received, but there could be other reasons.

Are the laptops AMD/Intel or NVIDIA/Intel graphics? The settings have to be for "high performance" globally, or set for the individual programs.

 Also what applications are you using ?

**Comment by creativewax** [comment]
Yeah it’s the virtual camera. And yes I understand the white noise when no signal. But like I said it randomly does it when there is a signal too. 

It seems to be mainly happening on a couple of laptops with Nvidia/Intel mix. 

I tried the high settings but didn’t seem to make much difference. Also I noticed in all instances that the spout demo sender seemed to work. 

I am using klak spout from unity. It seems to work fine on pretty much every setup I am using it on apart from the above.

**Comment by oppomobiles** [comment]
[Acer ENDURO N7](https://fivetech.co.uk/acer-enduro-n7-14-fhd-laptop-intel-core-i5-8250u-8gb-ram-256gb-ssd-win-10-pro.html) is the best Laptops with multiple GPUs. Engineered to withstand drops onto the hardest flooring, this rugged laptop has been constructed using shock-absorbent materials and independently certified to withstand drops, falls and water ingress. MIL-STD 810G and IP65 certification gives users the confidence that their equipment won’t be damaged.

**Comment by leadedge** [comment]
@creativewax

I have been through the SpoutCam code and the most likely reason for the static display is that SpoutCam is losing the sender for some reason.

The only thing I can think of is that there is some interruption of the application's access to NVIDIA graphics. The shotgun approach is to force all applications to use NVIDIA and that should work, but it's possible that you still have to set up a profile for the sender (Unity) as well as the program that uses SpoutCam.

I have to close this because I can't offer any solution, but please re-open if there is anything new that you find.
