### ISSUE TITLE
GL-Spout-NDI-DX ?

### ISSUE THREAD

**Issue by antithing** [leadedge/Spout2#78]
Hi, and thank you for making this code available. I have an application that plays several 4k videos and I would like to extend it as follows:
for each video:

Video playback in GL.
GL texture -> Spout
Spout -> over NDI to a different PC per video
NDI->DirectX texture for playback in a DX application.

Does this seem feasible? Do you happen to have example code for any of these functions?

Thanks!

**Comment by leadedge** [comment]
All of these things seem feasible.

The [SpoutToNDI](https://github.com/leadedge/leadedge.github.io/raw/downloads/SPOUTtoNDI_2008.zip) application could be useful.

GL texture > Spout > NDI has a few links in the chain that would reduce performance at 4K resolution, although 30 fps might be possible. The main holdup is getting pixel data from the GPU.

An Openframeworks video player application could use the [ofxNDI addon](https://github.com/leadedge/ofxNDI) to send NDI directly and avoid the intermediate Spout step.

NDI to DirectX texture is a possibility, although I don't have a working example. I would start by looking at a [Spout receiver example](https://github.com/leadedge/Spout2/tree/master/SPOUTSDK/SpoutDirectX/SpoutDX/Windows/Receiver) that transfers pixel data. This potentially could be modified to receive NDI rather than Spout. A sub-set of the ofxNDI addon can be used that does not depend on Openframeworks.

**Comment by antithing** [comment]
Thank you! I'll look into this further. Much appreciated.

**Comment by leadedge** [comment]
Do you need any more help with these suggestions?

It occurs to me that you would have to allow for line stride of the staging textures. There are functions in SpoutCopy.cpp that allow for this.
