### ISSUE TITLE
Global registry settings

### ISSUE THREAD

**Issue by Harvey3141** [leadedge/Spout2#79]
Hi, 

Currently the Spout registry settings are saved and loaded from 

Computer\HKEY_CURRENT_USER\SOFTWARE\Leading Edge\Spout

Which allows each Windows user to have their own Spout settings. 

A draw back to this approach is that if a machine is part of a corporate network and is using Active Directory, then any new user logging in must apply the Spout settings again. 

Moving the settings to the local machine path would fix this

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Leading Edge\Spout

A work around is to run a batch file on Windows login to set the registry settings manually

Thanks,
Harvey

**Comment by leadedge** [comment]
Hello Harvey,

I have used HKEY_CURRENT_USER thoughout to avoid permission issues. I haven't revisited this for a while but I expect the same problems to arise. If a batch file would solve this it might be the easiest way.

After the user applies the settings, do they remain in the registry or are they lost or changed when the user logs out?

Defaults should normally be OK (click Reset in SpoutSettings to see them). The only other problem could be the path to SpoutPanel, although I expect that most applications would not use it. The program sets it's own location when first run. Or you can copy it to the location of the receiver that uses it.

**Comment by leadedge** [comment]
I looked into this a little more and changing to HKEY_LOCAL_MACHINE is not an option due to the required privileges.

If a new user runs SpoutSettings at least once to establish the user registry settings, and these settings remain for that user when they log out and in again, I am not sure why you need the batch file on Windows start. Do you want each user to have the same settings?

There is more that can be done using the "Reset"/"Reload" functions and things like command-line arguments and starting with Windows could be done as well. But I need to understand more clearly what you want to do.

**Comment by leadedge** [comment]
I hope you have solved your requirements. Contact me by email if I can help with anything.
